# a_tensor_initialization.ipynb

In [ ]:
import torch
'''
torch.Tensor 클래스와 기본 속성 확인
'''
# torch.Tensor class
# 1, 2, 3 총 3개의 요소를 가진 1차원 tensor 생성
# device는 cpu로 명시적 지정.
t1 = torch.Tensor([1, 2, 3], device='cpu')
# print(t1) # 내용물 확인
print(t1.dtype)   # >>> torch.float32
print(t1.device)  # >>> cpu, 위에서 cpu를 명시적으로 지정해줬으므로
print(t1.requires_grad)  # >>> False, 자동 미분. 즉 그래디언트를 계산하는지 여부임.
print(t1.size())  # torch.Size([3]), 크기
print(t1.shape)   # torch.Size([3]), 모양

torch.float32
cpu
False
torch.Size([3])
torch.Size([3])


In [ ]:
'''
GPU가 사용가능하다면 GPU로 tensor를 이동하는 코드
'''
# if you have gpu device
# t1_cuda = t1.to(torch.device('cuda')) # tensor를 GPU로 이동
# or you can use shorthand
# t1_cuda = t1.cuda()
t1_cpu = t1.cpu() # tensor를 CPU로 이동

print("#" * 50, 1)

################################################## 1


In [ ]:
'''
이전 앞에 두 셀과 동일한 내용의 코드
'''
# torch.tensor function
t2 = torch.tensor([1, 2, 3], device='cpu')
print(t2.dtype)  # >>> torch.int64
print(t2.device)  # >>> cpu
print(t2.requires_grad)  # >>> False
print(t2.size())  # torch.Size([3])
print(t2.shape)  # torch.Size([3])

# if you have gpu device
# t2_cuda = t2.to(torch.device('cuda'))
# or you can use shorthand
# t2_cuda = t2.cuda()
t2_cpu = t2.cpu()

print("#" * 50, 2)

torch.int64
cpu
False
torch.Size([3])
torch.Size([3])
################################################## 2


In [ ]:
'''
Scalar tensor
'''
a1 = torch.tensor(1)			     # shape: torch.Size([]), ndims(=rank): 0
print(a1) # 출력 : tensor(1) > 정수 1을 의미
print(a1.shape, a1.ndim) # 스칼라 값이므로 차원이 없음.

'''
1 Dimension tensors
'''
a2 = torch.tensor([1])		  	     # shape: torch.Size([1]), ndims(=rank): 1
print(a2.shape, a2.ndim) # 모양 1, 차원 1

a3 = torch.tensor([1, 2, 3, 4, 5])   # shape: torch.Size([5]), ndims(=rank): 1
print(a3.shape, a3.ndim) # 모양 5, 차원 1

'''
2 Dimension tensors
'''
a4 = torch.tensor([[1], [2], [3], [4], [5]])   # shape: torch.Size([5, 1]), ndims(=rank): 2
print(a4.shape, a4.ndim) # 모양(5,1), 차원 2

a5 = torch.tensor([                 # shape: torch.Size([3, 2]), ndims(=rank): 2
    [1, 2],
    [3, 4],
    [5, 6]
])
print(a5.shape, a5.ndim) # 모양(3,2), 차원 2

'''
3 Dimension tensor
'''
a6 = torch.tensor([                 # shape: torch.Size([3, 2, 1]), ndims(=rank): 3
    [[1], [2]],
    [[3], [4]],
    [[5], [6]]
])
print(a6.shape, a6.ndim) # 모양(3,2,1) 차원 : 3

'''
4 Dimension tensors
'''
a7 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 1]), ndims(=rank): 4
    [[[1], [2]]],
    [[[3], [4]]],
    [[[5], [6]]]
])
print(a7.shape, a7.ndim) # 모양(3,1,2,1) 차원 : 4

a8 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3]), ndims(=rank): 4
    [[[1, 2, 3], [2, 3, 4]]],
    [[[3, 1, 1], [4, 4, 5]]],
    [[[5, 6, 2], [6, 3, 1]]]
])
print(a8.shape, a8.ndim) # 모양(3, 1, 2, 3) 차원 : 4

'''
5 Dimension tensors
'''
a9 = torch.tensor([                 # shape: torch.Size([3, 1, 2, 3, 1]), ndims(=rank): 5
    [[[[1], [2], [3]], [[2], [3], [4]]]],
    [[[[3], [1], [1]], [[4], [4], [5]]]],
    [[[[5], [6], [2]], [[6], [3], [1]]]]
])
print(a9.shape, a9.ndim) # 모양(3,1,2,3,1) 차원 : 5

tensor(1)
torch.Size([]) 0
torch.Size([1]) 1
torch.Size([5]) 1
torch.Size([5, 1]) 2
torch.Size([3, 2]) 2
torch.Size([3, 2, 1]) 3
torch.Size([3, 1, 2, 1]) 4
torch.Size([3, 1, 2, 3]) 4
torch.Size([3, 1, 2, 3, 1]) 5


In [ ]:
''' 2차원 텐서 '''
a10 = torch.tensor([                 # shape: torch.Size([4, 5]), ndims(=rank): 2
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
    [1, 2, 3, 4, 5],
])
print(a10.shape, a10.ndim) # 모양 (4, 5) 차원 : 2

''' 3차원 텐서 '''
a10 = torch.tensor([                 # shape: torch.Size([4, 1, 5]), ndims(=rank): 3
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
    [[1, 2, 3, 4, 5]],
])
print(a10.shape, a10.ndim) # 모양 (4,1,5) 차원 : 3

''' 오류 발생 '''
# 리스트의 길이가 일관되지 않기 때문.
a11 = torch.tensor([                 # ValueError: expected sequence of length 3 at dim 3 (got 2)
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
    [[[1, 2, 3], [4, 5]]],
])

torch.Size([4, 5]) 2
torch.Size([4, 1, 5]) 3


ValueError: expected sequence of length 3 at dim 3 (got 2)

# b_tensor_initialization_copy.ipynb

In [ ]:
import torch
import numpy as np

''' 리스트로부터 tensor 생성'''
# 생성된 텐서들은 list와 메모리를 공유하지 않음
# pass by reference가 아닌 pass by value
# 단, numpy를 as_tensor로 변환하는 경우 pass by reference

l1 = [1, 2, 3]
t1 = torch.Tensor(l1) # default type : torch.float32

l2 = [1, 2, 3]
t2 = torch.tensor(l2) # default type : 입력 값에 맞게 지정. 지금은 int

#as_tensor은 입력이 리스트나 파이썬의 기본 구조일 경우 연동 안됨.
l3 = [1, 2, 3]
t3 = torch.as_tensor(l3) #주어진 입력을 tensor로 변환

l1[0] = 100 # list의 값을 변경해도
l2[0] = 100 # 텐서의 값은 바뀌지 않음
l3[0] = 100

print(t1)
print(t2)
print(t3)

print("#" * 100)


tensor([1., 2., 3.])
tensor([1, 2, 3])
tensor([1, 2, 3])
####################################################################################################


In [ ]:
# Tensor와 tensor은 np.array로 생성한 배열이여도 메모리 공유 X
# 기타 사항 상기 코드와 동일
l4 = np.array([1, 2, 3])
t4 = torch.Tensor(l4)

l5 = np.array([1, 2, 3])
t5 = torch.tensor(l5)

# as_tensor은 가능한 경우(numpy 배열) 입력 데이터와 메모리를 공유하려 함.
# numpy 배열과는 같은 메모리를 참조한다는 뜻 (ndarray 변경시 텐서도 변경됨)
l6 = np.array([1, 2, 3])
t6 = torch.as_tensor(l6)

l4[0] = 100
l5[0] = 100
l6[0] = 100

print(t4)
print(t5)
print(t6)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)
tensor([100,   2,   3], dtype=torch.int32)


# c_tensor_initialization_constant_values.ipynb

In [ ]:
import torch
# 모든 요소가 1인 크기 (5,) 텐서 생성
t1 = torch.ones(size = (5,))  # or torch.ones(5)
# t1과 같은 크기를 갖고 모든 요소가 1인 텐서 생성
t1_like = torch.ones_like(input = t1)
print(t1, t1.shape)  # >>> tensor([1., 1., 1., 1., 1.])
print(t1_like, t1_like.shape)  # >>> tensor([1., 1., 1., 1., 1.])

tensor([1., 1., 1., 1., 1.]) torch.Size([5])
tensor([1., 1., 1., 1., 1.]) torch.Size([5])


In [ ]:
# 모든 요소가 0인 크기 (6,) 텐서 생성.
t2 = torch.zeros(size=(6,))  # or torch.zeros(6)
# t2와 같은 크기를 갖고 모든 요소가 0인 텐서 생성
t2_like = torch.zeros_like(input=t2)
# t2와 같은 크기를 갖고 모든 요소가 1인 텐서 생성
t2_like_ones = torch.ones_like(input=t2)
print(t2, t2.shape)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like, t2_like.shape)  # >>> tensor([0., 0., 0., 0., 0., 0.])
print(t2_like_ones, t2_like_ones.shape) #정말 내용을 복사하는 게 아닌 크기만 따라함을 알 수 있음.

tensor([0., 0., 0., 0., 0., 0.]) torch.Size([6])
tensor([0., 0., 0., 0., 0., 0.]) torch.Size([6])
tensor([1., 1., 1., 1., 1., 1.]) torch.Size([6])


In [ ]:
# empty는 초기화 해주지 않음!!!!

# 모든 요소가 임의의 값으로 되어있는 크기 (4,) 텐서 생성.
t3 = torch.empty(size=(4,))  # or torch.zeros(4)
# t3와 같은 크기와 데이터 타입을 갖고 모든 요소가 임의의 값으로 되어있는 텐서 생성
t3_like = torch.empty_like(input=t3)
print(t3)  # >>> tensor([n1., n2., n3., n4.])
print(t3_like)  # >>> tensor([a1., a2., a3., a4.])

tensor([0.0000, 2.1250, 3.0000, 0.0000])
tensor([0.0000, 1.8750, 3.0000, 0.0000])


In [ ]:
# 3by3 단위 행렬 생성
t4 = torch.eye(n=3)
print(t4)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


# d_tensor_initialization_random_values.ipynb

In [ ]:
import torch
# 10이상 20미만의 정수 난수들로 채워진 (1,2) 2차원 텐서 생성
t1 = torch.randint(low=10, high=20, size=(1, 2))
print(t1, t1.shape, t1.ndim)

# 0과 1사이의 균등분포 실수 난수로 채워진 (1,3) 2차원 텐서 생성
t2 = torch.rand(size=(1, 3))
print(t2, t2.shape, t2.ndim)

# 평균이 0, 표준편차가 1인 정규분포의 실수 난수로 채워진 (1,3) 2차원 텐서 생성
t3 = torch.randn(size=(1, 3))
print(t3, t3.shape, t3.ndim)

# 평균 10.0, 표준 편차 1.0인 정규분포 실수 난수로 채워진 (3,2) 2차원 텐서 생성
t4 = torch.normal(mean=10.0, std=1.0, size=(3, 2))
print(t4, t4.shape, t4.ndim)

# 0.0부터 5.0까지 구간을 동일한 간격의 3개의 요소로 채워진 1차원 텐서 생성
t5 = torch.linspace(start=0.0, end=5.0, steps=3)
print(t5, t5.shape, t5.ndim)

# 일정 간격의 수열 생성.
# 기본 값 start = 0, step_size = 1
# 즉 0부터 5 미만까지 1간격의 1차원 텐서 생성
t6 = torch.arange(5)
print(t6, t6.shape, t6.ndim)

print("#" * 30)


tensor([[13, 19]]) torch.Size([1, 2]) 2
tensor([[0.4160, 0.4784, 0.1479]]) torch.Size([1, 3]) 2
tensor([[-0.0201, -0.7571, -0.5000]]) torch.Size([1, 3]) 2
tensor([[11.5358, 10.4427],
        [10.6750, 10.7060],
        [ 9.7849, 10.2289]]) torch.Size([3, 2]) 2
tensor([0.0000, 2.5000, 5.0000]) torch.Size([3]) 1
tensor([0, 1, 2, 3, 4]) torch.Size([5]) 1
##############################


In [ ]:
torch.manual_seed(1729) # 난수 생성 시드 고정 -> 재현성 보장. 다른 환경에서도 손쉽게 같은 난수값 획득 가능

random1 = torch.rand(2, 3) # 0과 1사이의 균등 분포에서 실수 난수 생성
print(random1, random1.shape, random1.ndim)

random2 = torch.rand(2, 3) # 같은 시드로 설정한 난수 생성기를 연속으로 호출하면 값이 바뀜.
print(random2, random2.shape, random2.ndim)

print()

# 동일한 시드에 균등분포 적용하므로 위와 내용 동일
torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3, random3.shape, random3.ndim)

random4 = torch.rand(2, 3)
print(random4, random4.shape, random4.ndim)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]]) torch.Size([2, 3]) 2
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]]) torch.Size([2, 3]) 2

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]]) torch.Size([2, 3]) 2
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]]) torch.Size([2, 3]) 2


# e_tensor_type_conversion.ipynb

In [ ]:
import torch
# 모든 요소가 1인 (2,3) tensor
a = torch.ones((2, 3))
print(a.dtype) # torch.float32
b = torch.ones((2, 3), dtype=torch.int16) # 타입 명시적 지정
print(b) # torch.int16

# 0과 20사이의 난수를 가지는 (2,3) tensor
c = torch.rand((2, 3), dtype=torch.float64) * 20.
print(c)
c_int = c.to(torch.int32) # 추가 코드. 강제적 타입 변환
print(c_int)

d = b.to(torch.int32) # b tensor int32형으로 변경
print(d)


torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[18.0429,  7.2532, 19.6519],
        [10.8626,  2.1505, 19.6913]], dtype=torch.float64)
tensor([[18,  7, 19],
        [10,  2, 19]], dtype=torch.int32)
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [ ]:
''' 데이터 타입 지정하여 생성 '''
# double형의 1로만 채워진 (10,2) tensor
double_d = torch.ones(10, 2, dtype=torch.double)
# [1,2] list를 short형으로 변환한 tensor
short_e = torch.tensor([[1, 2]], dtype=torch.short)
print(double_d) # 출력은 float64다.
print(short_e) # 출력은 int16이다.
print()

''' 메소드 체인으로 타입 변경 '''
# double형의 0으로만 채워진 (10,2) tensor
double_d = torch.zeros(10, 2).double()
# short형의 1로만 채워진 (10,2) tensor
short_e = torch.ones(10, 2).short()
print(double_d) # 출력은 float64다.
print(short_e) # 출력은 int16이다.
print()

''' 데이터 타입 변경 메소드 to()'''
# double형의 0으로만 채워진 (10,2) tensor
double_d = torch.zeros(10, 2).to(torch.double)
# short형의 1로만 채워진 (10,2) tensor
short_e = torch.ones(10, 2).to(dtype=torch.short)
print(double_d) # 출력은 float64다.
print(short_e) # 출력은 int16이다.
print()

''' 데이터 타입 변경 메소드 type() '''
double_d = torch.zeros(10, 2).type(torch.double)
short_e = torch.ones(10, 2). type(dtype=torch.short)
print(double_d.dtype)
print(short_e.dtype)
print()

''' 데이터 타입 변환 후 연산 '''
# 크기가 5인 float64 난수 tensor 생성
double_f = torch.rand(5, dtype=torch.double)
print(double_f.dtype) #torch.float64
short_g = double_f.to(torch.short) #short로 형변환
print(short_g.dtype)  # torch.int16
print((double_f * short_g).dtype) # 실수 * 정수면 실수로 타입이 캐스트됨.

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)
tensor([[1, 2]], dtype=torch.int16)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]], dtype=torch.float64)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int

# f_tensor_operations.ipynb

In [ ]:
import torch
# 연산용 기본 데이터 생성, 확인
# 둘 다 1로 채워진 (2,3) tensor 생성
t1 = torch.ones(size=(2, 3))
t2 = torch.ones(size=(2, 3))
print(t1)
print(t2)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
''' 텐서의 덧셈 '''
#둘 다 동일하게 덧셈 연산이 이뤄짐
t3 = torch.add(t1, t2)
t4 = t1 + t2
print(t3)
print(t4)

print("#" * 30)

tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
##############################


In [ ]:
''' 텐서의 뺄셈 '''
#둘 다 동일하게 뺄셈 연산이 이뤄짐
t5 = torch.sub(t1, t2)
t6 = t1 - t2
print(t5)
print(t6)

print("#" * 30)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
##############################


In [ ]:
''' 텐서의 곱셈 '''
#둘 다 동일하게 곱셈 연산이 이뤄짐
t7 = torch.mul(t1, t2)
t8 = t1 * t2
print(t7)
print(t8)

print("#" * 30)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
##############################


In [ ]:
''' 텐서의 나눗셈 '''
#둘 다 동일하게 나눗셈 연산이 이뤄짐
t9 = torch.div(t1, t2)
t10 = t1 / t2
print(t9)
print(t10)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


# g_tensor_operations_mm.ipynb

In [ ]:
import torch
''' 내적 연산 '''
t1 = torch.dot(
  torch.tensor([2, 3]), torch.tensor([2, 1])
)
print(t1, t1.size()) #7, scalar 값이라 0 dimension


tensor(7) torch.Size([])


In [ ]:
''' 행렬곱 '''
#행렬곱을 하려면 앞의 열과 뒤의 행 크기가 같아야함.
t2 = torch.randn(2, 3) # 크기가 (2,3)인
t3 = torch.randn(3, 2) # 랜덤 실수 생성
print(t2)
print(t3)
t4 = torch.mm(t2, t3) #행렬곱 진행
print(t4, t4.size()) # 행렬곱 연산 결과는 앞의 행x뒤의 열이다.

tensor([[-1.9286, -1.1155,  2.2702],
        [ 0.1513, -0.6572,  0.0337]])
tensor([[ 0.5095, -1.2934],
        [ 0.0326, -1.9171],
        [ 1.1867, -1.0347]])
tensor([[1.6750, 2.2840],
        [0.0956, 1.0294]]) torch.Size([2, 2])


In [ ]:
''' 배치 행렬곱 '''
t5 = torch.randn(10, 3, 4) # 크기가 (10, 3, 4)인 랜덤 실수 텐서
t6 = torch.randn(10, 4, 5) # 크기가 (10, 4, 5)인 랜덤 실수 텐서
print(t5)
print(t6)
# 배치 행렬곱 수행
# t5와 t6에서 각각의 (3,4), (4,5) 행렬을 가져와 행렬곱함.
# 즉, 그 결과는 (10, 3, 5)
t7 = torch.bmm(t5, t6)
print(t7.size())

tensor([[[-0.2622, -0.7324, -1.5412,  1.7046],
         [-0.3845,  0.3328,  1.2672,  1.9288],
         [ 0.9224,  0.6983,  0.4298,  0.7367]],

        [[-0.6765, -1.6013,  1.4043,  0.0275],
         [ 1.1396,  0.8319, -2.8290,  0.7990],
         [-0.0259, -0.1426,  0.0289,  0.4560]],

        [[ 0.2564,  0.5316,  0.9480, -0.8093],
         [ 1.6049, -0.3759, -1.0110, -2.9320],
         [ 0.7230, -1.0887, -1.8443,  0.9148]],

        [[-1.3802, -2.2965, -0.1057,  1.1269],
         [-0.0881, -1.5910,  1.1006,  0.4278],
         [ 0.3104,  0.7605, -0.1078, -0.4368]],

        [[ 0.1931, -0.7604, -0.3729, -0.3506],
         [ 0.6184, -0.8416,  1.1644, -0.0788],
         [-1.1480,  1.0007, -1.1884, -0.7783]],

        [[-0.2389,  0.2970, -0.5581, -0.0832],
         [-1.2782,  0.4728, -0.4541,  0.4006],
         [ 0.3103, -0.8570, -0.5487, -0.5895]],

        [[ 0.5791,  1.0235, -1.2904, -1.0635],
         [ 1.2939,  0.6420,  1.3072, -0.6527],
         [-0.4425, -0.0483, -1.5344,  0.4059]],


# h_tensor_operations_matmul.ipynb

In [ ]:
import torch

# vector x vector: dot product (벡터 간의 내적 연산)
t1 = torch.randn(3)  # 크기가 3인 1차원 텐서 (벡터)를 생성
t2 = torch.randn(3)  # 크기가 3인 또 다른 1차원 텐서 (벡터)를 생성
print(torch.matmul(t1, t2).size())  # 두 벡터의 점곱 결과, 크기는 스칼라 (torch.Size([]))

# matrix x vector: broadcasted dot (행렬과 벡터 간의 곱)
t3 = torch.randn(3, 4)  # 크기가 (3, 4)인 2차원 텐서 (행렬)를 생성
t4 = torch.randn(4)     # 크기가 4인 1차원 텐서 (벡터)를 생성
print(torch.matmul(t3, t4).size())  # 행렬과 벡터 간의 곱셈 결과, 크기는 (3,)


torch.Size([])
torch.Size([3])


In [ ]:
# batched matrix x vector: broadcasted dot (배치 행렬과 벡터 간의 곱)
t5 = torch.randn(10, 3, 4)  # 크기가 (10, 3, 4)인 배치 형태의 텐서 (10개의 (3, 4) 행렬)를 생성
t6 = torch.randn(4)         # 크기가 4인 1차원 텐서 (벡터)를 생성
print(torch.matmul(t5, t6).size())  # 각 배치별로 행렬과 벡터 간의 곱셈, 결과 크기는 (10, 3)

# batched matrix x batched matrix: bmm (배치 행렬들 간의 곱셈)
t7 = torch.randn(10, 3, 4)  # 크기가 (10, 3, 4)인 배치 형태의 텐서 (10개의 (3, 4) 행렬)를 생성
t8 = torch.randn(10, 4, 5)  # 크기가 (10, 4, 5)인 배치 형태의 텐서 (10개의 (4, 5) 행렬)를 생성
print(torch.matmul(t7, t8).size())  # 각 배치별로 행렬곱, 결과 크기는 (10, 3, 5)

# batched matrix x matrix: bmm (배치 행렬과 일반 행렬 간의 곱셈)
t9 = torch.randn(10, 3, 4)  # 크기가 (10, 3, 4)인 배치 형태의 텐서 (10개의 (3, 4) 행렬)를 생성
t10 = torch.randn(4, 5)     # 크기가 (4, 5)인 2차원 텐서 (행렬)를 생성
print(torch.matmul(t9, t10).size())  # 각 배치별로 행렬곱, 결과 크기는 (10, 3, 5)

torch.Size([10, 3])
torch.Size([10, 3, 5])
torch.Size([10, 3, 5])


# i_tensor_broadcasting.ipynb

In [ ]:
import torch

# 스칼라와 텐서의 곱셈
t1 = torch.tensor([1.0, 2.0, 3.0])  # 크기 (3,)의 1차원 텐서 생성
t2 = 2.0  # 스칼라 값
print(t1 * t2)  # 각 요소에 스칼라 값을 곱하여 결과 텐서를 반환

print("#" * 50, 1)

tensor([2., 4., 6.])
################################################## 1


In [ ]:
# 브로드캐스팅을 이용한 텐서 간 연산
t3 = torch.tensor([[0, 1], [2, 4], [10, 10]])  # 크기 (3, 2)의 2차원 텐서 생성
t4 = torch.tensor([4, 5])  # 크기 (2,)의 1차원 텐서
print(t3 - t4)  # t4가 t3의 각 행에 브로드캐스트되어 요소별로 뺄셈 연산 수행

print("#" * 50, 2)

tensor([[-4, -4],
        [-2, -1],
        [ 6,  5]])
################################################## 2


In [ ]:
#다양한 산술 연산
t5 = torch.tensor([[1., 2.], [3., 4.]])  # 크기 (2, 2)의 2차원 텐서 생성
print(t5 + 2.0)  # 각 요소에 2.0을 더하는 연산 (add)
print(t5 - 2.0)  # 각 요소에서 2.0을 빼는 연산 (sub)
print(t5 * 2.0)  # 각 요소에 2.0을 곱하는 연산 (mul)
print(t5 / 2.0)  # 각 요소를 2.0으로 나누는 연산 (div)

print("#" * 50, 3)

tensor([[3., 4.],
        [5., 6.]])
tensor([[-1.,  0.],
        [ 1.,  2.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]])
################################################## 3


In [ ]:
# 텐서 정규화 함수
def normalize(x):
  return x / 255  # 입력 텐서를 255로 나누어 정규화

t6 = torch.randn(3, 28, 28)  # 크기 (3, 28, 28)의 랜덤 텐서 생성 (예: 이미지 3채널)
print(normalize(t6).size())  # 정규화 후 크기를 출력

print("#" * 50, 4)

torch.Size([3, 28, 28])
################################################## 4


In [ ]:
# 브로드캐스팅을 이용한 다양한 크기의 텐서 간 연산
t7 = torch.tensor([[1, 2], [0, 3]])  # 크기 (2, 2)의 텐서
t8 = torch.tensor([[3, 1]])  # 크기 (1, 2)의 텐서
t9 = torch.tensor([[5], [2]])  # 크기 (2, 1)의 텐서
t10 = torch.tensor([7])  # 크기 (1,)의 텐서
print(t7 + t8)   # t8이 t7에 브로드캐스트되어 요소별로 더함
print(t7 + t9)   # t9가 t7에 브로드캐스트되어 요소별로 더함
print(t8 + t9)   # t9가 t8에 브로드캐스트되어 요소별로 더함
print(t7 + t10)  # t10이 t7에 브로드캐스트되어 요소별로 더함

print("#" * 50, 5)

tensor([[4, 3],
        [3, 4]])
tensor([[6, 7],
        [2, 5]])
tensor([[8, 6],
        [5, 3]])
tensor([[ 8,  9],
        [ 7, 10]])
################################################## 5


In [ ]:
# 다차원 텐서 간 브로드캐스팅을 이용한 연산
t11 = torch.ones(4, 3, 2)  # 크기 (4, 3, 2)의 텐서
t12 = t11 * torch.rand(3, 2)  # 2번째와 3번째 차원이 t11과 동일, 첫 번째 차원이 없음 (브로드캐스트)
print(t12.shape)  # 결과는 (4, 3, 2)

t13 = torch.ones(4, 3, 2)
t14 = t13 * torch.rand(3, 1)  # 2번째 차원만 동일하고, 3번째 차원이 1 (브로드캐스트)
print(t14.shape)  # 결과는 (4, 3, 2)

t15 = torch.ones(4, 3, 2)
t16 = t15 * torch.rand(1, 2)  # 3번째 차원만 동일하고, 2번째 차원이 1 (브로드캐스트)
print(t16.shape)  # 결과는 (4, 3, 2)

t17 = torch.ones(5, 3, 4, 1)
t18 = torch.rand(3, 1, 1)  # 2번째 차원이 동일하고, 3, 4번째 차원이 1 (브로드캐스트)
print((t17 + t18).size())  # 결과는 (5, 3, 4, 1)

print("#" * 50, 6)

t19 = torch.empty(5, 1, 4, 1)  # 크기 (5, 1, 4, 1)의 텐서
t20 = torch.empty(3, 1, 1)  # 크기 (3, 1, 1)의 텐서
print((t19 + t20).size())  # 브로드캐스팅 후 결과 크기는 (5, 3, 4, 1)

t21 = torch.empty(1)  # 크기 (1)의 텐서
t22 = torch.empty(3, 1, 7)  # 크기 (3, 1, 7)의 텐서
print((t21 + t22).size())  # 브로드캐스팅 후 결과 크기는 (3, 1, 7)

t23 = torch.ones(3, 3, 3)  # 크기 (3, 3, 3)의 텐서
t24 = torch.ones(3, 1, 3)  # 크기 (3, 1, 3)의 텐서
print((t23 + t24).size())  # 브로드캐스팅 후 결과 크기는 (3, 3, 3)

# 아래 코드는 브로드캐스트가 실패하는 예시임 (추가 코드)
# t25 = torch.empty(5, 2, 4, 1)
# t26 = torch.empty(3, 1, 1)
# print((t25 + t26).size())
# RuntimeError: 텐서의 크기가 맞지 않기 때문에 오류 발생

print("#" * 50, 7)


torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([4, 3, 2])
torch.Size([5, 3, 4, 1])
################################################## 6
torch.Size([5, 3, 4, 1])
torch.Size([3, 1, 7])
torch.Size([3, 3, 3])
################################################## 7


In [ ]:
# 텐서의 지수와 제곱 연산
t27 = torch.ones(4) * 5  # 모든 요소가 5인 텐서 생성
print(t27)  # 출력: tensor([5, 5, 5, 5])

t28 = torch.pow(t27, 2)  # 각 요소를 제곱하여 새로운 텐서 생성
print(t28)  # 출력: tensor([25, 25, 25, 25])

exp = torch.arange(1., 5.)  # 크기 (4,)인 텐서 생성 [1., 2., 3., 4.]
a = torch.arange(1., 5.)  # 크기 (4,)인 텐서 생성 [1., 2., 3., 4.]
t29 = torch.pow(a, exp)  # 각 요소를 exp에 대응되는 값만큼 제곱
print(t29)  # 출력: tensor([1., 4., 27., 256.])  각각 1^1, 2^2, 3^3, 4^4


tensor([5., 5., 5., 5.])
tensor([25., 25., 25., 25.])
tensor([  1.,   4.,  27., 256.])


# j_tensor_indexing_slicing.ipynb

In [ ]:
import torch

''' 텐서의 인덱싱 및 슬라이싱 '''
x = torch.tensor(
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9],
   [10, 11, 12, 13, 14]]
)

# x[1]은 2차원 텐서에서 두 번째 행을 선택, 결과는 [5, 6, 7, 8, 9]
print(x[1])  # >>> tensor([5, 6, 7, 8, 9])

# x[:, 1]은 모든 행에서 두 번째 열을 선택, 결과는 [1, 6, 11]
print(x[:, 1])  # >>> tensor([1, 6, 11])

# x[1, 2]는 두 번째 행, 세 번째 열의 값을 선택, 결과는 7
print(x[1, 2])  # >>> tensor(7)

# x[:, -1]은 모든 행에서 마지막 열을 선택, 결과는 [4, 9, 14]
print(x[:, -1])  # >>> tensor([4, 9, 14])

print("#" * 50, 1)

tensor([5, 6, 7, 8, 9])
tensor([ 1,  6, 11])
tensor(7)
tensor([ 4,  9, 14])
################################################## 1


In [ ]:
''' 텐서의 슬라이싱을 통한 부분 선택 '''
# x[1:]은 두 번째 행부터 마지막 행까지 선택
print(x[1:])  # >>> tensor([[ 5,  6,  7,  8,  9], [10, 11, 12, 13, 14]])

# x[1:, 3:]은 두 번째 행부터 마지막 행의 세 번째 열 이후의 열을 선택
print(x[1:, 3:])  # >>> tensor([[ 8,  9], [13, 14]])

print("#" * 50, 2)

tensor([[ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])
tensor([[ 8,  9],
        [13, 14]])
################################################## 2


In [ ]:
''' 텐서의 특정 위치 값 변경 '''
y = torch.zeros((6, 6))  # 크기 (6, 6)의 0으로 채워진 텐서 생성

# y[1:4, 2] = 1: 두 번째 열의 두 번째부터 네 번째 행까지 1로 값 변경
y[1:4, 2] = 1
print(y)

# y[1:4, 1:4]: 두 번째부터 네 번째 행, 첫 번째부터 네 번째 열까지 선택하여 부분 텐서 출력
print(y[1:4, 1:4])  # 선택된 서브 텐서 출력

print("#" * 50, 3)

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])
tensor([[0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.]])
################################################## 3


In [ ]:
''' 텐서의 값 선택 및 수정 '''
z = torch.tensor(
  [[1, 2, 3, 4],
   [2, 3, 4, 5],
   [5, 6, 7, 8]]
)

# z[:2]는 첫 번째와 두 번째 행을 선택
print(z[:2])  # >>> tensor([[1, 2, 3, 4], [2, 3, 4, 5]])

# z[1:, 1:3]은 두 번째 행부터 마지막 행까지의 두 번째와 세 번째 열을 선택
print(z[1:, 1:3])  # >>> tensor([[3, 4], [6, 7]])

# z[:, 1:]은 모든 행의 두 번째 열부터 마지막 열까지 선택
print(z[:, 1:])  # >>> tensor([[2, 3, 4], [3, 4, 5], [6, 7, 8]])

# z[1:, 1:3] = 0: 두 번째 행부터 마지막 행까지의 두 번째와 세 번째 열을 0으로 변경
z[1:, 1:3] = 0
print(z)  # 변경된 z 출력, 선택된 부분이 0으로 바뀜


tensor([[1, 2, 3, 4],
        [2, 3, 4, 5]])
tensor([[3, 4],
        [6, 7]])
tensor([[2, 3, 4],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[1, 2, 3, 4],
        [2, 0, 0, 5],
        [5, 0, 0, 8]])


# k_tensor_reshaping.ipynb

In [ ]:
import torch

''' 텐서의 뷰(view)와 리쉐이프(reshape) '''
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 크기 (2, 3)의 텐서 생성
t2 = t1.view(3, 2)  # 텐서를 (3, 2)로 뷰 변경
t3 = t1.reshape(1, 6)  # 텐서를 (1, 6)으로 리쉐이프
print(t2)  # >>> tensor([[1, 2], [3, 4], [5, 6]])
print(t3)  # >>> tensor([[1, 2, 3, 4, 5, 6]])

t4 = torch.arange(8).view(2, 4)  # 0부터 7까지의 값을 갖는 (2, 4) 텐서 생성
t5 = torch.arange(6).view(2, 3)  # 0부터 5까지의 값을 갖는 (2, 3) 텐서 생성
print(t4)  # >>> tensor([[0, 1, 2, 3], [4, 5, 6, 7]])
print(t5)  # >>> tensor([[0, 1, 2], [3, 4, 5]])

print("#" * 50, 1)


tensor([[1, 2],
        [3, 4],
        [5, 6]])
tensor([[1, 2, 3, 4, 5, 6]])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2],
        [3, 4, 5]])
################################################## 1


In [ ]:
''' 텐서의 차원 축소 (squeeze) '''
# 크기가 (1, 3, 1)인 텐서 생성
t6 = torch.tensor([[[1], [2], [3]]])

# 크기가 1인 모든 차원을 제거, 결과는 (3,)
t7 = t6.squeeze()
# 0번째 차원(가장 바깥 차원)만 제거, 결과는 (3, 1)
t8 = t6.squeeze(0)
print(t7)  # >>> tensor([1, 2, 3])
print(t8)  # >>> tensor([[1], [2], [3]])

print("#" * 50, 2)


tensor([1, 2, 3])
tensor([[1],
        [2],
        [3]])
################################################## 2


In [ ]:
''' 텐서의 차원 확장 (unsqueeze) '''
# 크기가 (3,)인 텐서 생성
t9 = torch.tensor([1, 2, 3])

# 1번째 차원에 새로운 차원을 추가, 결과는 (3, 1)
t10 = t9.unsqueeze(1)
print(t10)  # >>> tensor([[1], [2], [3]])

# 크기가 (2, 3)인 텐서 생성
t11 = torch.tensor(
  [[1, 2, 3],
   [4, 5, 6]]
)

# 1번째 차원에 새로운 차원을 추가, 결과는 (2, 1, 3)
t12 = t11.unsqueeze(1)
print(t12, t12.shape)  # >>> tensor([[[1, 2, 3]], [[4, 5, 6]]]), torch.Size([2, 1, 3])

print("#" * 50, 3)

tensor([[1],
        [2],
        [3]])
tensor([[[1, 2, 3]],

        [[4, 5, 6]]]) torch.Size([2, 1, 3])
################################################## 3


In [ ]:
''' 텐서 평탄화 (flatten) '''
# 크기 (2, 3)인 텐서 생성
t13 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 텐서를 1차원으로 평탄화, 결과는 (6,)
t14 = t13.flatten()
print(t14)  # >>> tensor([1, 2, 3, 4, 5, 6])

# 크기가 (2, 2, 2)인 3차원 텐서 생성
t15 = torch.tensor([[[1, 2],
                     [3, 4]],
                    [[5, 6],
                     [7, 8]]])

# 전체를 평탄화, 결과는 (8,)
t16 = torch.flatten(t15)

# 두 번째 차원부터 평탄화, 결과는 (2, 4)
t17 = torch.flatten(t15, start_dim=1)
print(t16)  # >>> tensor([1, 2, 3, 4, 5, 6, 7, 8])
print(t17)  # >>> tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

print("#" * 50, 4)

tensor([1, 2, 3, 4, 5, 6])
tensor([1, 2, 3, 4, 5, 6, 7, 8])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
################################################## 4


In [ ]:
''' 텐서 차원 변경 (permute)와 전치 (transpose) '''
# 크기 (2, 3, 5)인 랜덤 텐서 생성
t18 = torch.randn(2, 3, 5)
print(t18.shape)  # >>> torch.Size([2, 3, 5])

# 차원을 (2, 0, 1)로 변경, 결과는 (5, 2, 3)
print(torch.permute(t18, (2, 0, 1)).size())  # >>> torch.Size([5, 2, 3])

# 크기 (2, 3)인 텐서 생성
t19 = torch.tensor([[1, 2, 3], [4, 5, 6]])

# 차원을 그대로 유지 (결과는 동일)
t20 = torch.permute(t19, dims=(0, 1))  # 결과는 (2, 3)

# 차원을 전치하여 (3, 2)로 변경
t21 = torch.permute(t19, dims=(1, 0))
print(t20)  # >>> tensor([[1, 2, 3], [4, 5, 6]])
print(t21)  # >>> tensor([[1, 4], [2, 5], [3, 6]])

# transpose()로 텐서의 차원을 전치, 결과는 (3, 2)
t22 = torch.transpose(t19, 0, 1)
print(t22)  # >>> tensor([[1, 4], [2, 5], [3, 6]])

# t() 함수로 2차원 텐서 전치, 결과는 (3, 2)
t23 = torch.t(t19)
print(t23)  # >>> tensor([[1, 4], [2, 5], [3, 6]])

torch.Size([2, 3, 5])
torch.Size([5, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


# l_tensor_concat.ipynb

In [ ]:
import torch
''' 3차원 텐서의 병합 (concat)'''
# 세 개의 3차원 텐서를 생성, 크기가 각각 다름
t1 = torch.zeros([2, 1, 3])  # 크기 (2, 1, 3)
t2 = torch.zeros([2, 3, 3])  # 크기 (2, 3, 3)
t3 = torch.zeros([2, 2, 3])  # 크기 (2, 2, 3)

# 세 개의 텐서를 1번째 차원을 기준으로 병합
t4 = torch.cat([t1, t2, t3], dim=1)
print(t4.shape)  # >>> torch.Size([2, 6, 3])
# t1, t2, t3가 1번째 차원을 따라 이어붙여져 크기 (2, 6, 3)이 됨

print("#" * 50, 1)


torch.Size([2, 6, 3])
################################################## 1


In [ ]:
'''1차원 텐서의 병합'''
# 두 개의 1차원 텐서 생성
t5 = torch.arange(0, 3)  # tensor([0, 1, 2])
t6 = torch.arange(3, 8)  # tensor([3, 4, 5, 6, 7])

# 두 개의 1차원 텐서를 dim=0에서 병합, 즉 이어붙임
t7 = torch.cat((t5, t6), dim=0)
print(t7.shape)  # >>> torch.Size([8])
print(t7)  # >>> tensor([0, 1, 2, 3, 4, 5, 6, 7])

print("#" * 50, 2)


torch.Size([8])
tensor([0, 1, 2, 3, 4, 5, 6, 7])
################################################## 2


In [ ]:
'''2차원 텐서의 병합'''
# 두 개의 2차원 텐서 생성
t8 = torch.arange(0, 6).reshape(2, 3)  # 크기 (2, 3)
t9 = torch.arange(6, 12).reshape(2, 3)  # 크기 (2, 3)

# 첫 번째 차원(dim=0)에서 병합, 행 방향으로 이어붙임
t10 = torch.cat((t8, t9), dim=0)
print(t10.size())  # >>> torch.Size([4, 3])
print(t10)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11]])

# 두 번째 차원(dim=1)에서 병합, 열 방향으로 이어붙임
t11 = torch.cat((t8, t9), dim=1)
print(t11.size())  # >>> torch.Size([2, 6])
print(t11)
# >>> tensor([[ 0,  1,  2,  6,  7,  8],
#             [ 3,  4,  5,  9, 10, 11]])

print("#" * 50, 3)



torch.Size([4, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  1,  2,  6,  7,  8],
        [ 3,  4,  5,  9, 10, 11]])
################################################## 3


In [ ]:
'''다수의 2차원 텐서 병합'''
# 세 개의 2차원 텐서 생성
t12 = torch.arange(0, 6).reshape(2, 3)  # 크기 (2, 3)
t13 = torch.arange(6, 12).reshape(2, 3)  # 크기 (2, 3)
t14 = torch.arange(12, 18).reshape(2, 3)  # 크기 (2, 3)

# 첫 번째 차원(dim=0)에서 세 개의 텐서를 병합
t15 = torch.cat((t12, t13, t14), dim=0)
print(t15.size())  # >>> torch.Size([6, 3])
print(t15)
# >>> tensor([[ 0,  1,  2],
#             [ 3,  4,  5],
#             [ 6,  7,  8],
#             [ 9, 10, 11],
#             [12, 13, 14],
#             [15, 16, 17]])

# 두 번째 차원(dim=1)에서 세 개의 텐서를 병합
t16 = torch.cat((t12, t13, t14), dim=1)
print(t16.size())  # >>> torch.Size([2, 9])
print(t16)
# >>> tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
#             [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])

print("#" * 50, 4)


torch.Size([6, 3])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])
torch.Size([2, 9])
tensor([[ 0,  1,  2,  6,  7,  8, 12, 13, 14],
        [ 3,  4,  5,  9, 10, 11, 15, 16, 17]])
################################################## 4


In [ ]:
'''3차원 텐서의 병합'''
# 두 개의 3차원 텐서 생성
t17 = torch.arange(0, 6).reshape(1, 2, 3)  # 크기 (1, 2, 3)
t18 = torch.arange(6, 12).reshape(1, 2, 3)  # 크기 (1, 2, 3)

# 첫 번째 차원(dim=0)에서 병합, 결과는 (2, 2, 3)
t19 = torch.cat((t17, t18), dim=0)
print(t19.size())  # >>> torch.Size([2, 2, 3])
print(t19)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5]],
#             [[ 6,  7,  8],
#              [ 9, 10, 11]]])

# 두 번째 차원(dim=1)에서 병합, 결과는 (1, 4, 3)
t20 = torch.cat((t17, t18), dim=1)
print(t20.size())  # >>> torch.Size([1, 4, 3])
print(t20)
# >>> tensor([[[ 0,  1,  2],
#              [ 3,  4,  5],
#              [ 6,  7,  8],
#              [ 9, 10, 11]]])

# 세 번째 차원(dim=2)에서 병합, 결과는 (1, 2, 6)
t21 = torch.cat((t17, t18), dim=2)
print(t21.size())  # >>> torch.Size([1, 2, 6])
print(t21)
# >>> tensor([[[ 0,  1,  2,  6,  7,  8],
#              [ 3,  4,  5,  9, 10, 11]]])

torch.Size([2, 2, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 4, 3])
tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]])
torch.Size([1, 2, 6])
tensor([[[ 0,  1,  2,  6,  7,  8],
         [ 3,  4,  5,  9, 10, 11]]])


# m_tensor_stacking.ipynb

In [ ]:
import torch

''' stack과 cat의 차이 '''
# 두 개의 2차원 텐서를 생성
t1 = torch.tensor([[1, 2, 3], [4, 5, 6]])  # 크기 (2, 3)
t2 = torch.tensor([[7, 8, 9], [10, 11, 12]])  # 크기 (2, 3)

# torch.stack: 텐서들을 새로운 차원에서 쌓음 (dim=0에서 쌓기)
t3 = torch.stack([t1, t2], dim=0)  # 결과 크기 (2, 2, 3)
# torch.cat: 먼저 텐서의 차원을 증가시킨 후 그 차원에서 이어붙이기
t4 = torch.cat([t1.unsqueeze(dim=0), t2.unsqueeze(dim=0)], dim=0)
print(t3.shape, t3.equal(t4))  # >>> torch.Size([2, 2, 3]) True

# torch.stack: 두 번째 차원에서 텐서들을 쌓기
t5 = torch.stack([t1, t2], dim=1)  # 결과 크기 (2, 2, 3)
# torch.cat: 텐서의 두 번째 차원에 이어붙임
t6 = torch.cat([t1.unsqueeze(dim=1), t2.unsqueeze(dim=1)], dim=1)
print(t5.shape, t5.equal(t6))  # >>> torch.Size([2, 2, 3]) True

# torch.stack: 세 번째 차원에서 텐서들을 쌓기
t7 = torch.stack([t1, t2], dim=2)  # 결과 크기 (2, 3, 2)
# torch.cat: 세 번째 차원에서 이어붙임
t8 = torch.cat([t1.unsqueeze(dim=2), t2.unsqueeze(dim=2)], dim=2)
print(t7.shape, t7.equal(t8))  # >>> torch.Size([2, 3, 2]) True

print("#" * 50, 1)

torch.Size([2, 2, 3]) True
torch.Size([2, 2, 3]) True
torch.Size([2, 3, 2]) True
################################################## 1


In [ ]:
'''1차원 텐서의 stack과 cat 비교'''
# 두 개의 1차원 텐서 생성
t9 = torch.arange(0, 3)  # tensor([0, 1, 2])
t10 = torch.arange(3, 6)  # tensor([3, 4, 5])

print(t9.size(), t10.size())  # >>> torch.Size([3]) torch.Size([3])

# torch.stack: 첫 번째 차원에서 두 텐서를 쌓음
t11 = torch.stack((t9, t10), dim=0)  # 결과 크기 (2, 3)
print(t11.size())  # >>> torch.Size([2, 3])
print(t11)
# >>> tensor([[0, 1, 2],
#             [3, 4, 5]])

# torch.cat: 각 텐서를 2차원으로 변환한 후 이어붙임
t12 = torch.cat((t9.unsqueeze(0), t10.unsqueeze(0)), dim=0)
print(t11.equal(t12))  # >>> True

# torch.stack: 두 번째 차원에서 두 텐서를 쌓음
t13 = torch.stack((t9, t10), dim=1)  # 결과 크기 (3, 2)
print(t13.size())  # >>> torch.Size([3, 2])
print(t13)
# >>> tensor([[0, 3],
#             [1, 4],
#             [2, 5]])

# torch.cat: 각 텐서를 2차원으로 변환한 후 두 번째 차원에서 이어붙임
t14 = torch.cat((t9.unsqueeze(1), t10.unsqueeze(1)), dim=1)
print(t13.equal(t14))  # >>> True


torch.Size([3]) torch.Size([3])
torch.Size([2, 3])
tensor([[0, 1, 2],
        [3, 4, 5]])
True
torch.Size([3, 2])
tensor([[0, 3],
        [1, 4],
        [2, 5]])
True


# n_tensor_vstack_hstack.ipynb

In [ ]:
import torch

'''1차원 텐서의 수직 결합 (vstack)'''
# 두 개의 1차원 텐서 생성
t1 = torch.tensor([1, 2, 3])  # 크기 (3,)
t2 = torch.tensor([4, 5, 6])  # 크기 (3,)

# torch.vstack: 두 개의 1차원 텐서를 수직으로 쌓아 2차원 텐서로 변환
t3 = torch.vstack((t1, t2))
print(t3)
# >>> tensor([[1, 2, 3],
#             [4, 5, 6]])
# 결과는 (2, 3) 크기의 2차원 텐서

# 두 개의 2차원 텐서 생성 (각 텐서가 하나의 열을 가짐)
t4 = torch.tensor([[1], [2], [3]])  # 크기 (3, 1)
t5 = torch.tensor([[4], [5], [6]])  # 크기 (3, 1)

# torch.vstack: 두 개의 2차원 텐서를 수직으로 결합
t6 = torch.vstack((t4, t5))
print(t6)
# >>> tensor([[1],
#             [2],
#             [3],
#             [4],
#             [5],
#             [6]])
# 결과는 (6, 1) 크기의 2차원 텐서

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])


In [ ]:
'''3차원 텐서의 수직 결합 (vstack)'''
# 크기 (2, 2, 3)의 3차원 텐서 생성
t7 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t7.shape)
# >>> torch.Size([2, 2, 3])

# 또 다른 크기 (2, 2, 3)의 3차원 텐서 생성
t8 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t8.shape)
# >>> torch.Size([2, 2, 3])

# torch.vstack: 두 개의 3차원 텐서를 첫 번째 차원에서 수직으로 결합
t9 = torch.vstack([t7, t8])
print(t9.shape)
# >>> torch.Size([4, 2, 3])
print(t9)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6]],
#             [[ 7,  8,  9],
#              [10, 11, 12]],
#             [[13, 14, 15],
#              [16, 17, 18]],
#             [[19, 20, 21],
#              [22, 23, 24]]])
# 결과는 (4, 2, 3) 크기의 3차원 텐서

print("#" * 50, 1)

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([4, 2, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24]]])
################################################## 1


In [ ]:
'''1차원 텐서의 수평 결합 (hstack)'''
# 두 개의 1차원 텐서 생성
t10 = torch.tensor([1, 2, 3])  # 크기 (3,)
t11 = torch.tensor([4, 5, 6])  # 크기 (3,)

# torch.hstack: 두 개의 1차원 텐서를 수평으로 결합하여 1차원으로 이어 붙임
t12 = torch.hstack((t10, t11))
print(t12)
# >>> tensor([1, 2, 3, 4, 5, 6])
# 결과는 (6,) 크기의 1차원 텐서

# 두 개의 2차원 텐서 생성 (각 텐서가 하나의 열을 가짐)
t13 = torch.tensor([[1], [2], [3]])  # 크기 (3, 1)
t14 = torch.tensor([[4], [5], [6]])  # 크기 (3, 1)

# torch.hstack: 두 개의 2차원 텐서를 수평으로 결합
t15 = torch.hstack((t13, t14))
print(t15)
# >>> tensor([[1, 4],
#             [2, 5],
#             [3, 6]])
# 결과는 (3, 2) 크기의 2차원 텐서

tensor([1, 2, 3, 4, 5, 6])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [ ]:
'''3차원 텐서의 수평 결합 (hstack)'''
# 크기 (2, 2, 3)의 3차원 텐서 생성
t16 = torch.tensor([
  [[1, 2, 3], [4, 5, 6]],
  [[7, 8, 9], [10, 11, 12]]
])
print(t16.shape)
# >>> torch.Size([2, 2, 3])

# 또 다른 크기 (2, 2, 3)의 3차원 텐서 생성
t17 = torch.tensor([
  [[13, 14, 15], [16, 17, 18]],
  [[19, 20, 21], [22, 23, 24]]
])
print(t17.shape)
# >>> torch.Size([2, 2, 3])

# torch.hstack: 두 개의 3차원 텐서를 두 번째 차원에서 수평으로 결합
t18 = torch.hstack([t16, t17])
print(t18.shape)
# >>> torch.Size([2, 4, 3])
print(t18)
# >>> tensor([[[ 1,  2,  3],
#              [ 4,  5,  6],
#              [13, 14, 15],
#              [16, 17, 18]],
#             [[ 7,  8,  9],
#              [10, 11, 12],
#              [19, 20, 21],
#              [22, 23, 24]]])
# 결과는 (2, 4, 3) 크기의 3차원 텐서

torch.Size([2, 2, 3])
torch.Size([2, 2, 3])
torch.Size([2, 4, 3])
tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [13, 14, 15],
         [16, 17, 18]],

        [[ 7,  8,  9],
         [10, 11, 12],
         [19, 20, 21],
         [22, 23, 24]]])


## 후기 및 인상 깊었던 부분
  이번 숙제를 하면서 처음으로 tensor를 써봤습니다. 대부분은 파이썬의 numpy와 비슷한 기능을 가지고 있어서 쉽게 익힐 수 있었는데 텐서를 생성하는 메소드가 여러개 있고, 이들의 특성이 각각 다르다는 점이 다른 자료형들(대표적으로 numpy, list)과 달라 신기했습니다.

**tensor를 torch.Tensor로 생성 시 요소의 default type이 float32입니다. torch.tenosr로 지정 시 처음 tensor에 입력된 값에 맞게 자료형이 지정됩니다. torch.as_tensor은 주어진 입력을 텐서로 변환합니다.**

이렇게 생성된 tensor는 list를 기반으로 생성했더라도 기반이 된 list와 메모리를 공유하지 않습니다. 이는 자료형이 ndarray여도 동일한데, 예외적으로 **as_tensor만 numpy를 텐서로 변환했을 경우 기반이 되는 ndarray와 메모리를 공유합니다.** 다른 리스트(또는 ndarray)을 복사하여 tensor화 하는데 기본적으로 pass by value로 진행된다는 점이 파이썬에서는 자주 찾아볼 수 없는 부분이라 신기했습니다.